// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxniuzhidizfkbgqkcev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4bml1emhpZGl6ZmtiZ3FrY2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjA5ODAsImV4cCI6MjA2NTc5Njk4MH0.K1YcsxkqsNJjixXe6W--UOjeE44pvbO6cMcKnuOrQg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);